GET http://localhost:3000/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InAxQGdtYWlsLmNvbSIsImlhdCI6MTYwMzYxMTU1NywiZXhwIjoxNjAzNjExNTg3fQ.Soc3q2WF7zRp80u6xGcFcNhfDq5gP6EpId1AEvy1XtQ

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "p1@gmail.com"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InAxQGdtYWlsLmNvbSIsImlhdCI6MTYwMzYxMTUyNH0.t6XDih4FCmU1CisBgZyeKLGYdOvX5mlgyFv-sTFU2g8"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InAxQGdtYWlsLmNvbSIsImlhdCI6MTYwMzYxMTUyNH0.t6XDih4FCmU1CisBgZyeKLGYdOvX5mlgyFv-sTFU2g8"
}